idf_component_register(SRCS 
                            "main.c"
                            "global_fn/global_var.c"
                            "ota_fn/ota_update_fn.c"
                            "eeprom_fn/id_storage.c"
                            "eeprom_fn/wifi_storage.c"
                            "eeprom_fn/schedule_storage.c"
                            "eeprom_fn/encoder_storage.c"
                            "websocket_fn/websocket_server_fn.c"
                            "websocket_fn/websocket_state_fn.c"
                            "time_fn/time_func.c"
                            "mqtt_fn/mqtt_client_fn.c"
                            "mqtt_fn/mqtt_state_fn.c"
                            "valve_fn/led_indicators.c"
                            "valve_fn/valve_motor.c"
                            "valve_fn/limit_switch.c"
                            "valve_fn/pot_read.c"
                            "valve_fn/valve_process.c"
                            "main_fn/main_process.c"
                            "webui_fn/webui_server.c"
                            "test_fn/test_process.c"
                        INCLUDE_DIRS 
                            "."
                        EMBED_TXTFILES
                            "mqtt_fn/ca_cert.pem"
                            "ota_fn/ota_ca_cert.pem"
                            "webui_fn/index.html"
                        REQUIRES 
                            esp_wifi 
                            mqtt 
                            nvs_flash 
                            json 
                            esp_http_server 
                            esp_https_ota
                            app_update
                            esp_http_client
                            esp_event
                            i2cdev
                            driver
                            )
